---
title: "Nesting Nooks: Exploring Squirrel Habitat"
output: 
  html_document:
    code_folding: hide
    always_allow_html: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
```

```{r, include = FALSE}
library(tidyverse)
library(plotly)
library(ggmap)
library(ggplot2)
library(sf)
library(tmap)
library(tmaptools)
```

Here we are loading in the data and a shapefile of Central Park!

```{r}
squirrel_census = 
  read_csv("data/clean_squirrel_2018.csv")
```

```{r}
central_park_map = st_read(here::here('central_park', 'CentralPark.shp'), quiet = TRUE)
```

#### Here is a map of the squirrels location by primary fur color!

```{r, fig.width= 6, fig.align='center'}
ggplot() +
  geom_sf(data = central_park_map, color = "grey") +
  geom_point(
    data = squirrel_census,
    aes(x = x, y = y, color = primary_fur_color),
    size = 0.5, alpha = 0.75) +
    theme_void(base_size = 15) +
  theme(legend.position = 'bottom') +
  guides(color = guide_legend(
    title.position = "top",
    override.aes = list(size = 3))) +
  labs(color = 'Primary Fur Color',
       title = 'Squirrel Fur Color Distribution') +
  scale_color_manual(values = c("Black" = "black", "Gray" = "azure4", "Cinnamon" = "darkorange3")) 
```

#### Here are all the hungry squirrels!

```{r, fig.width= 6, fig.align='center'}
squirrel_census |> 
  filter(eating == "TRUE") |> 
  ggplot() +
  geom_sf(data = central_park_map, color = "grey") +
  geom_point(
    aes(x = x, y = y, color = eating),
    size = 0.5, alpha = 0.75) +
    theme_void(base_size = 15) +
  theme(legend.position = 'none') +
  guides(color = guide_legend(
    title.position = "top",
    override.aes = list(size = 3))) +
  labs(title = "Hungry Squirrels and Where They Eat") +
  scale_color_manual(values = c("TRUE" = "coral"))
```

#### If they aren't eating, they are doing some other activity...

```{r, fig.width= 10, fig.align='center'}
squirrel_census |> 
  mutate(
    activity = case_when(
      running == "TRUE" ~ "running",
      chasing == "TRUE" ~ "chasing",
      climbing == "TRUE" ~ "climbing",
      foraging == "TRUE" ~ "foraging",
      .default = "sedintary"
    )
  ) |> 
  filter(activity != "sedintary") |> 
  ggplot() +
    geom_sf(data = central_park_map, color = "grey") +
  geom_point(
    aes(x = x, y = y, color = activity),
    size = 0.5, alpha = 0.75) +
    theme_void(base_size = 15) +
  theme(legend.position = 'bottom') +
  guides(color = guide_legend(
    title.position = "top",
    override.aes = list(size = 3))) +
  labs(
    title = "What are they doing?",
    color = "Squirrel Activities"
  ) +
  facet_grid(cols = vars(activity))
```


#### Eyes on the ground or to the trees to spot our furry friends?

```{r, fig.width= 6, fig.align='center'}
squirrel_census |> 
  ggplot() +
  geom_sf(data = central_park_map, color = "grey") +
  geom_point(
    aes(x = x, y = y, color = location),
    size = 0.5, alpha = 0.75) +
    theme_void(base_size = 15) +
  theme(legend.position = 'bottom') +
  guides(color = guide_legend(
    title.position = "top",
    override.aes = list(size = 3))) +
  labs(title = 'Up High or Down Low?',
       color = "Location")
```

```{r, fig.width= 6, fig.align='center'}
squirrel_census |> 
  filter(age != "?") |> 
  ggplot() +
  geom_sf(data = central_park_map, color = "grey") +
  geom_point(
    aes(x = x, y = y, color = age),
    size = 0.5, alpha = 0.75) +
    theme_void(base_size = 15) +
  theme(legend.position = 'bottom') +
  guides(color = guide_legend(
    title.position = "top",
    override.aes = list(size = 3))) +
  scale_color_manual(values = c("Adult" = "aquamarine3", "Juvenile" = "coral1")) +
  labs(title = "Squirrel Age",
       color = "Age")
```


```{r, fig.width= 6, fig.align='center'}
squirrel_census |> 
  mutate(
    activity = case_when(
      running == "TRUE" ~ "running",
      chasing == "TRUE" ~ "chasing",
      climbing == "TRUE" ~ "climbing",
      foraging == "TRUE" ~ "foraging",
      .default = "sedintary"
    )
  ) |> 
  plot_ly(
    x = ~x, y = ~y, type = "scatter", mode = "markers", color = ~primary_fur_color, text = ~paste(name, age, activity, sep = "<br />"), alpha = 0.5) |> 
    layout(xaxis = list(title = 'x',
                      showgrid = F,
                      zerolinecolor = '#ffff'
  ),
  yaxis = list(title = 'y',
               zerolinecolor = '#ffff',
               showgrid = F),
  plot_bgcolor='white')
```

